module.exports = {
  get: {
    '/logistics/statisticsDayExport': '/qiho/goodsExports.json',
    '/qiho/ads/item/dhour': '/qiho/qihoAdsItemDhour.json',
    '/qiho/item/dhour': '/qiho/qihoItemDhour.json',
    '/dataDownload/query': '/qiho/dataDownloadQuery.json',
    '/dataDownload/report': '/qiho/dataDownloadReport.json',
    '/qiho/advert/goods/di/findTotal/export': '/qiho/findTotalExport.json',
    '/qiho/advert/goods/di/find/export': '/qiho/findExport.json',
    '/qiho/advert/goods/di/merchant': '/qiho/getMerchantAll.json',
    '/qiho/advert/goods/di/item': '/qiho/getItemAll.json',
    '/qiho/advert/goods/di/advertId': '/qiho/getAdvAll.json'
  },
  post: {
    '/dataDownload/save': '/qiho/dataDownloadSave.json',
    '/logistics/queryStatisticsDayPage': '/qiho/tuiaGoodsList.json',
    '/logistics/queryAdvertStatisticsDayPage': '/qiho/tuiaAdplanList.json',
    '/logistics/queryAppStatisticsDayPage': '/qiho/tuiaMediasList.json',
    '/logistics/queryAdvertNumStatisticsDayPage': '/qiho/tuiaCouponList.json',
    '/logistics/orderChart': '/qiho/orderChart.json',
    '/logistics/statisticsTable': '/qiho/statisticsTable.json',
    '/logistics/statisticsGeneral': '/qiho/statisticsGeneral.json',
    '/logistics/statisticsItemTrend': '/qiho/statisticsItemTrend.json',
    '/sku/abtest': '/qiho/skuABTest.json',
    '/alarm/config/findByParam': '/qiho/alarmConfigList.json',
    '/alarm/config/getClickRate': '/qiho/getClickRate.json',
    '/alarm/config/saveClickRate': '/qiho/saveClickRate.json',
    '/alarm/config/getCpa': '/qiho/getCpa.json',
    '/alarm/config/saveCpa': '/qiho/saveCpa.json',
    '/alarm/config/getConsume': '/qiho/getConsume.json',
    '/alarm/config/saveConsume': '/qiho/saveConsume.json',
    '/alarm/record/findByParam': '/qiho/getAlarmList.json',
    '/alarm/config/delete': '/qiho/delAlarmConfig.json',
    '/qiho/advert/goods/di/findTotal': '/qiho/qihoOverallSerires.json',
    '/qiho/advert/goods/di/find': '/qiho/qihoOverallScatter.json',
    '/qiho/advert/goods/di/findTotal/list': '/qiho/getAccumedataList.json',
    '/qiho/advert/goods/di/find/list': '/qiho/getSlotdataList.json',
    '/ae/findByParam': '/qiho/getAEList.json',
    '/ae/delete': '/qiho/delAE.json',
    '/ae/save': '/qiho/save.json',
    '/ae/group/delete': '/qiho/save.json',
    '/ae/group/findByParam': '/qiho/aeGroupFind.json',
    '/ae/group/save': '/qiho/save.json',
    '/ae/ad/delete': '/qiho/save.json',
    '/ae/ad/findByParam': '/qiho/AdfindByParam.json',
    '/ae/ad/save': '/qiho/save.json'
  }
};
