module.exports = {
  get: {
    '/poackage/ads/loading/page/collect': '/tuia/adsLoading.json',
    '/ads/id': '/tuia/adsId.json',
    '/ads/name': '/tuia/adsName.json',
    '/poackage/ads/loading/page': '/tuia/adsLoadingPage.json',
    '/tuia/app/top/list': '/tuia/appList.json',
    '/tuia/adslot/app/top/list': '/tuia/adslotList.json',
    '/tuia/activity/app/top/list': '/tuia/actList.json',
    '/poackage/ads/loading/page/top/list': '/tuia/advList.json',
    '/tuia/app/info': '/tuia/tuiaappinfo.json',
    '/page/heatMap/getData': '/tuia/getData.json',
    '/page/heatMap/preview': '/tuia/preview.json',
    '/page/heatMap/getSkinTypeList': '/tuia/skin.json',
    '/slot/chain/user': '/tuia/roadMap.json',
    '/tuia/budget/balance': '/tuia/budgetBalance.json',
    '/tuia/budget/balance/top/list': '/tuia/budgetBalanceTopList.json',
    '/slot': '/tuia/tuiaslotinfo.json',
    '/airport/data': '/tuia/airport.json',
    '/trade': '/tuia/trade.json',
    '/trade/realtime': '/tuia/traderealtime.json'
  },
  post: {
    '/trade/realtime/data': '/tuia/traderealtimedata.json',
    '/rule/queryList': '/tuia/queryList.json',
    '/effect/analyse': '/tuia/adveffect.json',
    '/rule/add': '/tuia/rule.json',
    '/rule/editRule': '/tuia/rule.json',
    '/rule/preCheck': '/tuia/rule.json',
    '/rule/delete': '/tuia/rule.json',
    '/tuia/app/top': '/tuia/appRank.json',
    '/poackage/ads/loading/page/top': '/tuia/advRank.json',
    '/tuia/adslot/app/top': '/tuia/slotRank.json',
    '/tuia/activity/app/top': '/tuia/actRank.json',
    '/media/app': '/tuia/mediaApp.json',
    '/media/slot': '/tuia/mediaSlot.json',
    '/media/data': '/tuia/mediaData.json',
    '/domain': '/tuia/domain.json',
    '/domain/add': '/tuia/domainAdd.json',
    '/domain/edit': '/tuia/domainEdit.json',
    '/domain/remove': '/tuia/domainRemove.json',
    '/slot/analyse': '/tuia/slotanalyse.json',
    '/eyes/flow/effect/statistic': '/tuia/eyesfloweffect.json',
    // 大盘分析视图
    '/eyes/flow/effect/statistic/view': '/tuia/bigdata.json',
    // 广告计划分析视图
    '/effect/analyse/view': '/tuia/adview.json',
    // 落地页热力图明细数据
    '/page/heatMap/getLandPageDetailData': '/tuia/getLandPageDetailData.json',
    // 落地页热力图PV、UV数据
    '/page/heatMap/getLandData': '/tuia/getLandData.json',
    // 落地页热力图页面Id集合
    '/page/heatMap/getLandPageChildPageId': '/tuia/getLandPageChildPageId.json',
    // 热力图图片下载
    '/page/heatMap/getLandPagePic': '/tuia/getLandPagePic.json',

    '/ads/advance': '/tuia/adsAdvance.json',
    '/ads/basic': '/tuia/adsBasic.json',
    // 核心指标数据
    '/customizekb/coreDataValue': '/tuia/coreDataValue.json',
    '/customizekb/kanban/linechart': '/tuia/kanbanline.json',
    '/customizekb/kanban/piechart': '/kanbanpie.json',
    '/customizekb/kanban/chart': '/tuia/chartkanban.json',
    '/customizekb/mediakanban/': '/tuia/mediakanban.json',
    '/customizekb/advertkanban/': '/tuia/advertkanban.json',
    '/customizekb/traffickanban/': '/tuia/traffickkanban.json',
    '/trade/data': '/tuia/tradedata.json',
    '/ads/detail': '/tuia/adsDetail.json',
    '/ads/basic': '/tuia/adsBasic.json',
    '/ads/trade': '/tuia/adsTrade.json'
  }
};
